### ISSUE TITLE
AttributeError when running train.py

### ISSUE THREAD

**Issue by lxqpku** [YaoMarkMu/Vision-Transformer-for-Online-Reinforcement-Learning#1]
workspace: /home/username/ViT4RL/runs/2022.10.10/170928_action_repeat=2,batch_size=512,env=walker_walk
Traceback (most recent call last):
  File "train.py", line 185, in <module>
    main()
  File "/home/username/.conda/envs/drq/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/username/.conda/envs/drq/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/username/.conda/envs/drq/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/username/.conda/envs/drq/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 180, in main
    workspace = W(cfg)
  File "/home/username/ViT4RL/train.py", line 72, in __init__
    self.env = make_env(cfg)
  File "/home/username/ViT4RL/train.py", line 46, in make_env
    camera_id=camera_id)
  File "/home/username/.conda/envs/drq/lib/python3.7/site-packages/dmc2gym/__init__.py", line 28, in make
    if not env_id in gym.envs.registry.env_specs:
AttributeError: 'dict' object has no attribute 'env_specs'

**Comment by lxqpku** [comment]
> workspace: /home/username/ViT4RL/runs/2022.10.10/170928_action_repeat=2,batch_size=512,env=walker_walk Traceback (most recent call last): File "train.py", line 185, in main() File "/home/username/.conda/envs/drq/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main strict=strict, File "/home/username/.conda/envs/drq/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra overrides=args.overrides, File "/home/username/.conda/envs/drq/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run job_subdir_key=None, File "/home/username/.conda/envs/drq/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 109, in run_job ret.return_value = task_function(task_cfg) File "train.py", line 180, in main workspace = W(cfg) File "/home/username/ViT4RL/train.py", line 72, in **init** self.env = make_env(cfg) File "/home/username/ViT4RL/train.py", line 46, in make_env camera_id=camera_id) File "/home/username/.conda/envs/drq/lib/python3.7/site-packages/dmc2gym/**init**.py", line 28, in make if not env_id in gym.envs.registry.env_specs: AttributeError: 'dict' object has no attribute 'env_specs'

This issue was caused by MUJOCO environment, and now it has been resolved.
